// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package replication is a generated GoMock package.
package replication

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/transmogr/transmogr/internal/models"
)

// MockcryptoService is a mock of cryptoService interface.
type MockcryptoService struct {
	ctrl     *gomock.Controller
	recorder *MockcryptoServiceMockRecorder
}

// MockcryptoServiceMockRecorder is the mock recorder for MockcryptoService.
type MockcryptoServiceMockRecorder struct {
	mock *MockcryptoService
}

// NewMockcryptoService creates a new mock instance.
func NewMockcryptoService(ctrl *gomock.Controller) *MockcryptoService {
	mock := &MockcryptoService{ctrl: ctrl}
	mock.recorder = &MockcryptoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcryptoService) EXPECT() *MockcryptoServiceMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockcryptoService) Decrypt(ctx context.Context, table string, fields map[string][]byte) (map[string][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ctx, table, fields)
	ret0, _ := ret[0].(map[string][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockcryptoServiceMockRecorder) Decrypt(ctx, table, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockcryptoService)(nil).Decrypt), ctx, table, fields)
}

// Encrypt mocks base method.
func (m *MockcryptoService) Encrypt(ctx context.Context, table string, fields map[string][]byte) (map[string][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", ctx, table, fields)
	ret0, _ := ret[0].(map[string][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockcryptoServiceMockRecorder) Encrypt(ctx, table, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockcryptoService)(nil).Encrypt), ctx, table, fields)
}

// MocksnapshotService is a mock of snapshotService interface.
type MocksnapshotService struct {
	ctrl     *gomock.Controller
	recorder *MocksnapshotServiceMockRecorder
}

// MocksnapshotServiceMockRecorder is the mock recorder for MocksnapshotService.
type MocksnapshotServiceMockRecorder struct {
	mock *MocksnapshotService
}

// NewMocksnapshotService creates a new mock instance.
func NewMocksnapshotService(ctrl *gomock.Controller) *MocksnapshotService {
	mock := &MocksnapshotService{ctrl: ctrl}
	mock.recorder = &MocksnapshotServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksnapshotService) EXPECT() *MocksnapshotServiceMockRecorder {
	return m.recorder
}

// ApplyIncomingChunk mocks base method.
func (m *MocksnapshotService) ApplyIncomingChunk(ctx context.Context, peerRegion, table string, chunk models.SnapshotChunk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyIncomingChunk", ctx, peerRegion, table, chunk)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyIncomingChunk indicates an expected call of ApplyIncomingChunk.
func (mr *MocksnapshotServiceMockRecorder) ApplyIncomingChunk(ctx, peerRegion, table, chunk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyIncomingChunk", reflect.TypeOf((*MocksnapshotService)(nil).ApplyIncomingChunk), ctx, peerRegion, table, chunk)
}

// CompleteIncomingSnapshot mocks base method.
func (m *MocksnapshotService) CompleteIncomingSnapshot(ctx context.Context, peerRegion, table string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteIncomingSnapshot", ctx, peerRegion, table)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteIncomingSnapshot indicates an expected call of CompleteIncomingSnapshot.
func (mr *MocksnapshotServiceMockRecorder) CompleteIncomingSnapshot(ctx, peerRegion, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"CompleteIncomingSnapshot",
		reflect.TypeOf((*MocksnapshotService)(nil).CompleteIncomingSnapshot),
		ctx,
		peerRegion,
		table,
	)
}

// SendToPeer mocks base method.
func (m *MocksnapshotService) SendToPeer(
	ctx context.Context,
	peerRegion,
	table string,
	afterPrimaryKey []models.PrimaryKeyPart,
	send func(models.SnapshotChunk) error,
) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendToPeer", ctx, peerRegion, table, afterPrimaryKey, send)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendToPeer indicates an expected call of SendToPeer.
func (mr *MocksnapshotServiceMockRecorder) SendToPeer(ctx, peerRegion, table, afterPrimaryKey, send interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"SendToPeer",
		reflect.TypeOf((*MocksnapshotService)(nil).SendToPeer),
		ctx,
		peerRegion,
		table,
		afterPrimaryKey,
		send,
	)
}

// MockreplicationState is a mock of replicationState interface.
type MockreplicationState struct {
	ctrl     *gomock.Controller
	recorder *MockreplicationStateMockRecorder
}

// MockreplicationStateMockRecorder is the mock recorder for MockreplicationState.
type MockreplicationStateMockRecorder struct {
	mock *MockreplicationState
}

// NewMockreplicationState creates a new mock instance.
func NewMockreplicationState(ctrl *gomock.Controller) *MockreplicationState {
	mock := &MockreplicationState{ctrl: ctrl}
	mock.recorder = &MockreplicationStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreplicationState) EXPECT() *MockreplicationStateMockRecorder {
	return m.recorder
}

// CommitStateAppliedTransaction mocks base method.
func (m *MockreplicationState) CommitStateAppliedTransaction(ctx context.Context, events []models.ReplicationEvent, mode models.ReplicationApplyMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitStateAppliedTransaction", ctx, events, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitStateAppliedTransaction indicates an expected call of CommitStateAppliedTransaction.
func (mr *MockreplicationStateMockRecorder) CommitStateAppliedTransaction(ctx, events, mode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitStateAppliedTransaction", reflect.TypeOf((*MockreplicationState)(nil).CommitStateAppliedTransaction), ctx, events, mode)
}

// GetStateCursor mocks base method.
func (m *MockreplicationState) GetStateCursor(ctx context.Context, peerRegion, table string) (models.StateCursor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStateCursor", ctx, peerRegion, table)
	ret0, _ := ret[0].(models.StateCursor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStateCursor indicates an expected call of GetStateCursor.
func (mr *MockreplicationStateMockRecorder) GetStateCursor(ctx, peerRegion, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStateCursor", reflect.TypeOf((*MockreplicationState)(nil).GetStateCursor), ctx, peerRegion, table)
}

// GetStateSnapshotJob mocks base method.
func (m *MockreplicationState) GetStateSnapshotJob(ctx context.Context, peerRegion, table string) (models.StateSnapshotJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStateSnapshotJob", ctx, peerRegion, table)
	ret0, _ := ret[0].(models.StateSnapshotJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStateSnapshotJob indicates an expected call of GetStateSnapshotJob.
func (mr *MockreplicationStateMockRecorder) GetStateSnapshotJob(ctx, peerRegion, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStateSnapshotJob", reflect.TypeOf((*MockreplicationState)(nil).GetStateSnapshotJob), ctx, peerRegion, table)
}

// MockstreamBus is a mock of streamBus interface.
type MockstreamBus struct {
	ctrl     *gomock.Controller
	recorder *MockstreamBusMockRecorder
}

// MockstreamBusMockRecorder is the mock recorder for MockstreamBus.
type MockstreamBusMockRecorder struct {
	mock *MockstreamBus
}

// NewMockstreamBus creates a new mock instance.
func NewMockstreamBus(ctrl *gomock.Controller) *MockstreamBus {
	mock := &MockstreamBus{ctrl: ctrl}
	mock.recorder = &MockstreamBusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstreamBus) EXPECT() *MockstreamBusMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockstreamBus) Publish(ctx context.Context, peerRegion string, message models.StreamMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, peerRegion, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockstreamBusMockRecorder) Publish(ctx, peerRegion, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockstreamBus)(nil).Publish), ctx, peerRegion, message)
}

// Subscribe mocks base method.
func (m *MockstreamBus) Subscribe(ctx context.Context, peerRegion string) (<-chan models.StreamMessage, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, peerRegion)
	ret0, _ := ret[0].(<-chan models.StreamMessage)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockstreamBusMockRecorder) Subscribe(ctx, peerRegion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockstreamBus)(nil).Subscribe), ctx, peerRegion)
}
