// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package changefeed is a generated GoMock package.
package changefeed

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/transmogr/transmogr/internal/models"
)

// MockChangefeedMetrics is a mock of ChangefeedMetrics interface.
type MockChangefeedMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockChangefeedMetricsMockRecorder
}

// MockChangefeedMetricsMockRecorder is the mock recorder for MockChangefeedMetrics.
type MockChangefeedMetricsMockRecorder struct {
	mock *MockChangefeedMetrics
}

// NewMockChangefeedMetrics creates a new mock instance.
func NewMockChangefeedMetrics(ctrl *gomock.Controller) *MockChangefeedMetrics {
	mock := &MockChangefeedMetrics{ctrl: ctrl}
	mock.recorder = &MockChangefeedMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangefeedMetrics) EXPECT() *MockChangefeedMetricsMockRecorder {
	return m.recorder
}

// RecordChangefeedBatch mocks base method.
func (m *MockChangefeedMetrics) RecordChangefeedBatch() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordChangefeedBatch")
}

// RecordChangefeedBatch indicates an expected call of RecordChangefeedBatch.
func (mr *MockChangefeedMetricsMockRecorder) RecordChangefeedBatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordChangefeedBatch", reflect.TypeOf((*MockChangefeedMetrics)(nil).RecordChangefeedBatch))
}

// RecordChangefeedEvent mocks base method.
func (m *MockChangefeedMetrics) RecordChangefeedEvent() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordChangefeedEvent")
}

// RecordChangefeedEvent indicates an expected call of RecordChangefeedEvent.
func (mr *MockChangefeedMetricsMockRecorder) RecordChangefeedEvent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordChangefeedEvent", reflect.TypeOf((*MockChangefeedMetrics)(nil).RecordChangefeedEvent))
}

// MockOutbox is a mock of Outbox interface.
type MockOutbox struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxMockRecorder
}

// MockOutboxMockRecorder is the mock recorder for MockOutbox.
type MockOutboxMockRecorder struct {
	mock *MockOutbox
}

// NewMockOutbox creates a new mock instance.
func NewMockOutbox(ctrl *gomock.Controller) *MockOutbox {
	mock := &MockOutbox{ctrl: ctrl}
	mock.recorder = &MockOutboxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutbox) EXPECT() *MockOutboxMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockOutbox) Enqueue(ctx context.Context, batch models.OutboxBatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, batch)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockOutboxMockRecorder) Enqueue(ctx, batch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockOutbox)(nil).Enqueue), ctx, batch)
}

// NextSequence mocks base method.
func (m *MockOutbox) NextSequence(ctx context.Context, peerRegion, table string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextSequence", ctx, peerRegion, table)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextSequence indicates an expected call of NextSequence.
func (mr *MockOutboxMockRecorder) NextSequence(ctx, peerRegion, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextSequence", reflect.TypeOf((*MockOutbox)(nil).NextSequence), ctx, peerRegion, table)
}

// MockLeaseService is a mock of LeaseService interface.
type MockLeaseService struct {
	ctrl     *gomock.Controller
	recorder *MockLeaseServiceMockRecorder
}

// MockLeaseServiceMockRecorder is the mock recorder for MockLeaseService.
type MockLeaseServiceMockRecorder struct {
	mock *MockLeaseService
}

// NewMockLeaseService creates a new mock instance.
func NewMockLeaseService(ctrl *gomock.Controller) *MockLeaseService {
	mock := &MockLeaseService{ctrl: ctrl}
	mock.recorder = &MockLeaseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaseService) EXPECT() *MockLeaseServiceMockRecorder {
	return m.recorder
}

// RunWithLease mocks base method.
func (m *MockLeaseService) RunWithLease(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunWithLease", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunWithLease indicates an expected call of RunWithLease.
func (mr *MockLeaseServiceMockRecorder) RunWithLease(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWithLease", reflect.TypeOf((*MockLeaseService)(nil).RunWithLease), ctx, fn)
}

// MockPeersService is a mock of PeersService interface.
type MockPeersService struct {
	ctrl     *gomock.Controller
	recorder *MockPeersServiceMockRecorder
}

// MockPeersServiceMockRecorder is the mock recorder for MockPeersService.
type MockPeersServiceMockRecorder struct {
	mock *MockPeersService
}

// NewMockPeersService creates a new mock instance.
func NewMockPeersService(ctrl *gomock.Controller) *MockPeersService {
	mock := &MockPeersService{ctrl: ctrl}
	mock.recorder = &MockPeersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeersService) EXPECT() *MockPeersServiceMockRecorder {
	return m.recorder
}

// Peers mocks base method.
func (m *MockPeersService) Peers() []models.Peer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Peers")
	ret0, _ := ret[0].([]models.Peer)
	return ret0
}

// Peers indicates an expected call of Peers.
func (mr *MockPeersServiceMockRecorder) Peers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Peers", reflect.TypeOf((*MockPeersService)(nil).Peers))
}

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// CursorTables mocks base method.
func (m *MockAdapter) CursorTables() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorTables")
	ret0, _ := ret[0].([]string)
	return ret0
}

// CursorTables indicates an expected call of CursorTables.
func (mr *MockAdapterMockRecorder) CursorTables() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorTables", reflect.TypeOf((*MockAdapter)(nil).CursorTables))
}

// RestoreCursors mocks base method.
func (m *MockAdapter) RestoreCursors(ctx context.Context, load func(string) (models.ChangefeedCursor, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreCursors", ctx, load)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreCursors indicates an expected call of RestoreCursors.
func (mr *MockAdapterMockRecorder) RestoreCursors(ctx, load interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreCursors", reflect.TypeOf((*MockAdapter)(nil).RestoreCursors), ctx, load)
}

// Run mocks base method.
func (m *MockAdapter) Run(ctx context.Context, onBatch func(context.Context, models.ChangefeedBatch) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, onBatch)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockAdapterMockRecorder) Run(ctx, onBatch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockAdapter)(nil).Run), ctx, onBatch)
}

// MockStateStore is a mock of StateStore interface.
type MockStateStore struct {
	ctrl     *gomock.Controller
	recorder *MockStateStoreMockRecorder
}

// MockStateStoreMockRecorder is the mock recorder for MockStateStore.
type MockStateStoreMockRecorder struct {
	mock *MockStateStore
}

// NewMockStateStore creates a new mock instance.
func NewMockStateStore(ctrl *gomock.Controller) *MockStateStore {
	mock := &MockStateStore{ctrl: ctrl}
	mock.recorder = &MockStateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateStore) EXPECT() *MockStateStoreMockRecorder {
	return m.recorder
}

// GetChangefeedCursor mocks base method.
func (m *MockStateStore) GetChangefeedCursor(ctx context.Context, table string) (models.ChangefeedCursor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangefeedCursor", ctx, table)
	ret0, _ := ret[0].(models.ChangefeedCursor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangefeedCursor indicates an expected call of GetChangefeedCursor.
func (mr *MockStateStoreMockRecorder) GetChangefeedCursor(ctx, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangefeedCursor", reflect.TypeOf((*MockStateStore)(nil).GetChangefeedCursor), ctx, table)
}

// SaveChangefeedCursor mocks base method.
func (m *MockStateStore) SaveChangefeedCursor(ctx context.Context, cursor models.ChangefeedCursor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChangefeedCursor", ctx, cursor)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveChangefeedCursor indicates an expected call of SaveChangefeedCursor.
func (mr *MockStateStoreMockRecorder) SaveChangefeedCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChangefeedCursor", reflect.TypeOf((*MockStateStore)(nil).SaveChangefeedCursor), ctx, cursor)
}
