// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package outbox is a generated GoMock package.
package outbox

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "github.com/transmogr/transmogr/internal/models"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// OutboxAck mocks base method.
func (m *Mockrepository) OutboxAck(ctx context.Context, peerRegion, table, lastEventID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxAck", ctx, peerRegion, table, lastEventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OutboxAck indicates an expected call of OutboxAck.
func (mr *MockrepositoryMockRecorder) OutboxAck(ctx, peerRegion, table, lastEventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxAck", reflect.TypeOf((*Mockrepository)(nil).OutboxAck), ctx, peerRegion, table, lastEventID)
}

// OutboxCleanup mocks base method.
func (m *Mockrepository) OutboxCleanup(ctx context.Context, maxBatchAge time.Duration, maxPendingPerPeer int) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxCleanup", ctx, maxBatchAge, maxPendingPerPeer)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// OutboxCleanup indicates an expected call of OutboxCleanup.
func (mr *MockrepositoryMockRecorder) OutboxCleanup(ctx, maxBatchAge, maxPendingPerPeer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxCleanup", reflect.TypeOf((*Mockrepository)(nil).OutboxCleanup), ctx, maxBatchAge, maxPendingPerPeer)
}

// OutboxEnqueue mocks base method.
func (m *Mockrepository) OutboxEnqueue(ctx context.Context, batch models.OutboxBatch) (models.OutboxBatch, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxEnqueue", ctx, batch)
	ret0, _ := ret[0].(models.OutboxBatch)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// OutboxEnqueue indicates an expected call of OutboxEnqueue.
func (mr *MockrepositoryMockRecorder) OutboxEnqueue(ctx, batch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxEnqueue", reflect.TypeOf((*Mockrepository)(nil).OutboxEnqueue), ctx, batch)
}

// OutboxListPending mocks base method.
func (m *Mockrepository) OutboxListPending(ctx context.Context, peerRegion string, limit int) ([]models.OutboxBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxListPending", ctx, peerRegion, limit)
	ret0, _ := ret[0].([]models.OutboxBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OutboxListPending indicates an expected call of OutboxListPending.
func (mr *MockrepositoryMockRecorder) OutboxListPending(ctx, peerRegion, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxListPending", reflect.TypeOf((*Mockrepository)(nil).OutboxListPending), ctx, peerRegion, limit)
}

// OutboxListPendingWindow mocks base method.
func (m *Mockrepository) OutboxListPendingWindow(ctx context.Context, peerRegion string, lowerExclusive, upperInclusive time.Time, afterID uint64, limit int) ([]models.OutboxBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxListPendingWindow", ctx, peerRegion, lowerExclusive, upperInclusive, afterID, limit)
	ret0, _ := ret[0].([]models.OutboxBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OutboxListPendingWindow indicates an expected call of OutboxListPendingWindow.
func (mr *MockrepositoryMockRecorder) OutboxListPendingWindow(ctx, peerRegion, lowerExclusive, upperInclusive, afterID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxListPendingWindow", reflect.TypeOf((*Mockrepository)(nil).OutboxListPendingWindow), ctx, peerRegion, lowerExclusive, upperInclusive, afterID, limit)
}

// OutboxLoadMetricsSnapshot mocks base method.
func (m *Mockrepository) OutboxLoadMetricsSnapshot(ctx context.Context) (models.OutboxMetricsSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxLoadMetricsSnapshot", ctx)
	ret0, _ := ret[0].(models.OutboxMetricsSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OutboxLoadMetricsSnapshot indicates an expected call of OutboxLoadMetricsSnapshot.
func (mr *MockrepositoryMockRecorder) OutboxLoadMetricsSnapshot(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxLoadMetricsSnapshot", reflect.TypeOf((*Mockrepository)(nil).OutboxLoadMetricsSnapshot), ctx)
}

// OutboxNextSequence mocks base method.
func (m *Mockrepository) OutboxNextSequence(ctx context.Context, peerRegion, table string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxNextSequence", ctx, peerRegion, table)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OutboxNextSequence indicates an expected call of OutboxNextSequence.
func (mr *MockrepositoryMockRecorder) OutboxNextSequence(ctx, peerRegion, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxNextSequence", reflect.TypeOf((*Mockrepository)(nil).OutboxNextSequence), ctx, peerRegion, table)
}

// OutboxReady mocks base method.
func (m *Mockrepository) OutboxReady(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxReady", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// OutboxReady indicates an expected call of OutboxReady.
func (mr *MockrepositoryMockRecorder) OutboxReady(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxReady", reflect.TypeOf((*Mockrepository)(nil).OutboxReady), ctx)
}

// OutboxSnapshotWatermark mocks base method.
func (m *Mockrepository) OutboxSnapshotWatermark(ctx context.Context) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxSnapshotWatermark", ctx)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OutboxSnapshotWatermark indicates an expected call of OutboxSnapshotWatermark.
func (mr *MockrepositoryMockRecorder) OutboxSnapshotWatermark(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxSnapshotWatermark", reflect.TypeOf((*Mockrepository)(nil).OutboxSnapshotWatermark), ctx)
}
