// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package snapshot is a generated GoMock package.
package snapshot

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "github.com/transmogr/transmogr/internal/models"
)

// MocksnapshotState is a mock of snapshotState interface.
type MocksnapshotState struct {
	ctrl     *gomock.Controller
	recorder *MocksnapshotStateMockRecorder
}

// MocksnapshotStateMockRecorder is the mock recorder for MocksnapshotState.
type MocksnapshotStateMockRecorder struct {
	mock *MocksnapshotState
}

// NewMocksnapshotState creates a new mock instance.
func NewMocksnapshotState(ctrl *gomock.Controller) *MocksnapshotState {
	mock := &MocksnapshotState{ctrl: ctrl}
	mock.recorder = &MocksnapshotStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksnapshotState) EXPECT() *MocksnapshotStateMockRecorder {
	return m.recorder
}

// CommitStateSnapshotCheckpoint mocks base method.
func (m *MocksnapshotState) CommitStateSnapshotCheckpoint(ctx context.Context, job models.StateSnapshotJob) (models.CommitSnapshotCheckpointResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitStateSnapshotCheckpoint", ctx, job)
	ret0, _ := ret[0].(models.CommitSnapshotCheckpointResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitStateSnapshotCheckpoint indicates an expected call of CommitStateSnapshotCheckpoint.
func (mr *MocksnapshotStateMockRecorder) CommitStateSnapshotCheckpoint(ctx, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitStateSnapshotCheckpoint", reflect.TypeOf((*MocksnapshotState)(nil).CommitStateSnapshotCheckpoint), ctx, job)
}

// GetStateSnapshotJob mocks base method.
func (m *MocksnapshotState) GetStateSnapshotJob(ctx context.Context, peerRegion, table string) (models.StateSnapshotJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStateSnapshotJob", ctx, peerRegion, table)
	ret0, _ := ret[0].(models.StateSnapshotJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStateSnapshotJob indicates an expected call of GetStateSnapshotJob.
func (mr *MocksnapshotStateMockRecorder) GetStateSnapshotJob(ctx, peerRegion, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStateSnapshotJob", reflect.TypeOf((*MocksnapshotState)(nil).GetStateSnapshotJob), ctx, peerRegion, table)
}

// MarkStateSnapshotFinished mocks base method.
func (m *MocksnapshotState) MarkStateSnapshotFinished(ctx context.Context, peerRegion, table string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkStateSnapshotFinished", ctx, peerRegion, table)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkStateSnapshotFinished indicates an expected call of MarkStateSnapshotFinished.
func (mr *MocksnapshotStateMockRecorder) MarkStateSnapshotFinished(ctx, peerRegion, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkStateSnapshotFinished", reflect.TypeOf((*MocksnapshotState)(nil).MarkStateSnapshotFinished), ctx, peerRegion, table)
}

// ReleaseStateLease mocks base method.
func (m *MocksnapshotState) ReleaseStateLease(ctx context.Context, kind, region, peerRegion, table, ownerID string, generation int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseStateLease", ctx, kind, region, peerRegion, table, ownerID, generation)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseStateLease indicates an expected call of ReleaseStateLease.
func (mr *MocksnapshotStateMockRecorder) ReleaseStateLease(ctx, kind, region, peerRegion, table, ownerID, generation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseStateLease", reflect.TypeOf((*MocksnapshotState)(nil).ReleaseStateLease), ctx, kind, region, peerRegion, table, ownerID, generation)
}

// RenewStateLease mocks base method.
func (m *MocksnapshotState) RenewStateLease(ctx context.Context, kind, region, peerRegion, table, ownerID string, generation int64, ttl time.Duration) (models.Lease, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenewStateLease", ctx, kind, region, peerRegion, table, ownerID, generation, ttl)
	ret0, _ := ret[0].(models.Lease)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RenewStateLease indicates an expected call of RenewStateLease.
func (mr *MocksnapshotStateMockRecorder) RenewStateLease(ctx, kind, region, peerRegion, table, ownerID, generation, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewStateLease", reflect.TypeOf((*MocksnapshotState)(nil).RenewStateLease), ctx, kind, region, peerRegion, table, ownerID, generation, ttl)
}

// TryStateAcquireLease mocks base method.
func (m *MocksnapshotState) TryStateAcquireLease(ctx context.Context, kind, region, peerRegion, table, ownerID string, ttl time.Duration) (models.Lease, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryStateAcquireLease", ctx, kind, region, peerRegion, table, ownerID, ttl)
	ret0, _ := ret[0].(models.Lease)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TryStateAcquireLease indicates an expected call of TryStateAcquireLease.
func (mr *MocksnapshotStateMockRecorder) TryStateAcquireLease(ctx, kind, region, peerRegion, table, ownerID, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryStateAcquireLease", reflect.TypeOf((*MocksnapshotState)(nil).TryStateAcquireLease), ctx, kind, region, peerRegion, table, ownerID, ttl)
}

// UpsertStateSnapshotJob mocks base method.
func (m *MocksnapshotState) UpsertStateSnapshotJob(ctx context.Context, job models.StateSnapshotJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStateSnapshotJob", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertStateSnapshotJob indicates an expected call of UpsertStateSnapshotJob.
func (mr *MocksnapshotStateMockRecorder) UpsertStateSnapshotJob(ctx, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStateSnapshotJob", reflect.TypeOf((*MocksnapshotState)(nil).UpsertStateSnapshotJob), ctx, job)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ApplyIncomingChunk mocks base method.
func (m *MockService) ApplyIncomingChunk(ctx context.Context, peerRegion, table string, chunk models.SnapshotChunk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyIncomingChunk", ctx, peerRegion, table, chunk)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyIncomingChunk indicates an expected call of ApplyIncomingChunk.
func (mr *MockServiceMockRecorder) ApplyIncomingChunk(ctx, peerRegion, table, chunk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyIncomingChunk", reflect.TypeOf((*MockService)(nil).ApplyIncomingChunk), ctx, peerRegion, table, chunk)
}

// CompleteIncomingSnapshot mocks base method.
func (m *MockService) CompleteIncomingSnapshot(ctx context.Context, peerRegion, table string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteIncomingSnapshot", ctx, peerRegion, table)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteIncomingSnapshot indicates an expected call of CompleteIncomingSnapshot.
func (mr *MockServiceMockRecorder) CompleteIncomingSnapshot(ctx, peerRegion, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"CompleteIncomingSnapshot",
		reflect.TypeOf((*MockService)(nil).CompleteIncomingSnapshot),
		ctx,
		peerRegion,
		table,
	)
}

// SendToPeer mocks base method.
func (m *MockService) SendToPeer(
	ctx context.Context,
	peerRegion,
	table string,
	afterPrimaryKey []models.PrimaryKeyPart,
	send func(models.SnapshotChunk) error,
) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendToPeer", ctx, peerRegion, table, afterPrimaryKey, send)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendToPeer indicates an expected call of SendToPeer.
func (mr *MockServiceMockRecorder) SendToPeer(ctx, peerRegion, table, afterPrimaryKey, send interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"SendToPeer",
		reflect.TypeOf((*MockService)(nil).SendToPeer),
		ctx,
		peerRegion,
		table,
		afterPrimaryKey,
		send,
	)
}

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock *MockSource
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// ReadSnapshotChunk mocks base method.
func (m *MockSource) ReadSnapshotChunk(ctx context.Context, req models.SnapshotReadRequest) (models.SnapshotChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSnapshotChunk", ctx, req)
	ret0, _ := ret[0].(models.SnapshotChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSnapshotChunk indicates an expected call of ReadSnapshotChunk.
func (mr *MockSourceMockRecorder) ReadSnapshotChunk(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSnapshotChunk", reflect.TypeOf((*MockSource)(nil).ReadSnapshotChunk), ctx, req)
}

// MockApplier is a mock of Applier interface.
type MockApplier struct {
	ctrl     *gomock.Controller
	recorder *MockApplierMockRecorder
}

// MockApplierMockRecorder is the mock recorder for MockApplier.
type MockApplierMockRecorder struct {
	mock *MockApplier
}

// NewMockApplier creates a new mock instance.
func NewMockApplier(ctrl *gomock.Controller) *MockApplier {
	mock := &MockApplier{ctrl: ctrl}
	mock.recorder = &MockApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplier) EXPECT() *MockApplierMockRecorder {
	return m.recorder
}

// ApplySnapshotChunk mocks base method.
func (m *MockApplier) ApplySnapshotChunk(ctx context.Context, peerRegion, table string, rows []models.SnapshotRow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplySnapshotChunk", ctx, peerRegion, table, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplySnapshotChunk indicates an expected call of ApplySnapshotChunk.
func (mr *MockApplierMockRecorder) ApplySnapshotChunk(ctx, peerRegion, table, rows interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySnapshotChunk", reflect.TypeOf((*MockApplier)(nil).ApplySnapshotChunk), ctx, peerRegion, table, rows)
}
