// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package lease is a generated GoMock package.
package lease

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "github.com/transmogr/transmogr/internal/models"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ReleaseStateLease mocks base method.
func (m *MockStore) ReleaseStateLease(ctx context.Context, kind, region, peerRegion, table, ownerID string, generation int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseStateLease", ctx, kind, region, peerRegion, table, ownerID, generation)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseStateLease indicates an expected call of ReleaseStateLease.
func (mr *MockStoreMockRecorder) ReleaseStateLease(ctx, kind, region, peerRegion, table, ownerID, generation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseStateLease", reflect.TypeOf((*MockStore)(nil).ReleaseStateLease), ctx, kind, region, peerRegion, table, ownerID, generation)
}

// RenewStateLease mocks base method.
func (m *MockStore) RenewStateLease(ctx context.Context, kind, region, peerRegion, table, ownerID string, generation int64, ttl time.Duration) (models.Lease, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenewStateLease", ctx, kind, region, peerRegion, table, ownerID, generation, ttl)
	ret0, _ := ret[0].(models.Lease)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RenewStateLease indicates an expected call of RenewStateLease.
func (mr *MockStoreMockRecorder) RenewStateLease(ctx, kind, region, peerRegion, table, ownerID, generation, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewStateLease", reflect.TypeOf((*MockStore)(nil).RenewStateLease), ctx, kind, region, peerRegion, table, ownerID, generation, ttl)
}

// TryStateAcquireLease mocks base method.
func (m *MockStore) TryStateAcquireLease(ctx context.Context, kind, region, peerRegion, table, ownerID string, ttl time.Duration) (models.Lease, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryStateAcquireLease", ctx, kind, region, peerRegion, table, ownerID, ttl)
	ret0, _ := ret[0].(models.Lease)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TryStateAcquireLease indicates an expected call of TryStateAcquireLease.
func (mr *MockStoreMockRecorder) TryStateAcquireLease(ctx, kind, region, peerRegion, table, ownerID, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryStateAcquireLease", reflect.TypeOf((*MockStore)(nil).TryStateAcquireLease), ctx, kind, region, peerRegion, table, ownerID, ttl)
}
