// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/replication.proto

package peerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operation identifies the kind of row mutation.
type Event_Operation int32

const (
	Event_OPERATION_UNSPECIFIED Event_Operation = 0
	Event_OPERATION_INSERT      Event_Operation = 1
	Event_OPERATION_UPDATE      Event_Operation = 2
	Event_OPERATION_DELETE      Event_Operation = 3
)

// Enum value maps for Event_Operation.
var (
	Event_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_INSERT",
		2: "OPERATION_UPDATE",
		3: "OPERATION_DELETE",
	}
	Event_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_INSERT":      1,
		"OPERATION_UPDATE":      2,
		"OPERATION_DELETE":      3,
	}
)

func (x Event_Operation) Enum() *Event_Operation {
	p := new(Event_Operation)
	*p = x
	return p
}

func (x Event_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_replication_proto_enumTypes[0].Descriptor()
}

func (Event_Operation) Type() protoreflect.EnumType {
	return &file_v1_replication_proto_enumTypes[0]
}

func (x Event_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Operation.Descriptor instead.
func (Event_Operation) EnumDescriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{9, 0}
}

// ConsumeRequest identifies the consumer and advertises protocol compatibility.
type ConsumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// region is the consuming peer region identity.
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// version is the consuming peer version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// configuration is the consuming peer configuration fingerprint.
	Configuration string `protobuf:"bytes,3,opt,name=configuration,proto3" json:"configuration,omitempty"`
	// snapshot_requests carries per-table snapshot bootstrap requests.
	SnapshotRequests []*SnapshotRequest `protobuf:"bytes,4,rep,name=snapshot_requests,json=snapshotRequests,proto3" json:"snapshot_requests,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_v1_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumeRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ConsumeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConsumeRequest) GetConfiguration() string {
	if x != nil {
		return x.Configuration
	}
	return ""
}

func (x *ConsumeRequest) GetSnapshotRequests() []*SnapshotRequest {
	if x != nil {
		return x.SnapshotRequests
	}
	return nil
}

// SnapshotRequest requests snapshot bootstrap for one table, optionally resuming
// after the last durably applied primary key checkpoint on the consumer.
type SnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// table is the replicated table name.
	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// after_primary_key resumes snapshot reads strictly after this primary key.
	AfterPrimaryKey []*PrimaryKeyPart `protobuf:"bytes,2,rep,name=after_primary_key,json=afterPrimaryKey,proto3" json:"after_primary_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_v1_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SnapshotRequest) GetAfterPrimaryKey() []*PrimaryKeyPart {
	if x != nil {
		return x.AfterPrimaryKey
	}
	return nil
}

// ConsumeResponse is one envelope emitted by the serving peer.
type ConsumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ConsumeResponse_Handshake
	//	*ConsumeResponse_SnapshotChunk
	//	*ConsumeResponse_SnapshotComplete
	//	*ConsumeResponse_EventBatch
	//	*ConsumeResponse_TransactionBatch
	//	*ConsumeResponse_Heartbeat
	Msg           isConsumeResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_v1_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumeResponse) GetMsg() isConsumeResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ConsumeResponse) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Msg.(*ConsumeResponse_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *ConsumeResponse) GetSnapshotChunk() *SnapshotChunk {
	if x != nil {
		if x, ok := x.Msg.(*ConsumeResponse_SnapshotChunk); ok {
			return x.SnapshotChunk
		}
	}
	return nil
}

func (x *ConsumeResponse) GetSnapshotComplete() *SnapshotComplete {
	if x != nil {
		if x, ok := x.Msg.(*ConsumeResponse_SnapshotComplete); ok {
			return x.SnapshotComplete
		}
	}
	return nil
}

func (x *ConsumeResponse) GetEventBatch() *EventBatch {
	if x != nil {
		if x, ok := x.Msg.(*ConsumeResponse_EventBatch); ok {
			return x.EventBatch
		}
	}
	return nil
}

func (x *ConsumeResponse) GetTransactionBatch() *TransactionBatch {
	if x != nil {
		if x, ok := x.Msg.(*ConsumeResponse_TransactionBatch); ok {
			return x.TransactionBatch
		}
	}
	return nil
}

func (x *ConsumeResponse) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*ConsumeResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isConsumeResponse_Msg interface {
	isConsumeResponse_Msg()
}

type ConsumeResponse_Handshake struct {
	// handshake identifies the serving peer and confirms stream compatibility.
	Handshake *Handshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type ConsumeResponse_SnapshotChunk struct {
	// snapshot_chunk carries one chunk of snapshot rows.
	SnapshotChunk *SnapshotChunk `protobuf:"bytes,2,opt,name=snapshot_chunk,json=snapshotChunk,proto3,oneof"`
}

type ConsumeResponse_SnapshotComplete struct {
	// snapshot_complete marks the end of snapshot bootstrap for one table.
	SnapshotComplete *SnapshotComplete `protobuf:"bytes,6,opt,name=snapshot_complete,json=snapshotComplete,proto3,oneof"`
}

type ConsumeResponse_EventBatch struct {
	// event_batch carries ordered incremental replication events (polling path).
	EventBatch *EventBatch `protobuf:"bytes,3,opt,name=event_batch,json=eventBatch,proto3,oneof"`
}

type ConsumeResponse_TransactionBatch struct {
	// transaction_batch carries all events from one CDC source transaction (CDC path).
	TransactionBatch *TransactionBatch `protobuf:"bytes,4,opt,name=transaction_batch,json=transactionBatch,proto3,oneof"`
}

type ConsumeResponse_Heartbeat struct {
	// heartbeat keeps the stream alive and exposes sender time.
	Heartbeat *Heartbeat `protobuf:"bytes,5,opt,name=heartbeat,proto3,oneof"`
}

func (*ConsumeResponse_Handshake) isConsumeResponse_Msg() {}

func (*ConsumeResponse_SnapshotChunk) isConsumeResponse_Msg() {}

func (*ConsumeResponse_SnapshotComplete) isConsumeResponse_Msg() {}

func (*ConsumeResponse_EventBatch) isConsumeResponse_Msg() {}

func (*ConsumeResponse_TransactionBatch) isConsumeResponse_Msg() {}

func (*ConsumeResponse_Heartbeat) isConsumeResponse_Msg() {}

type SnapshotComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotComplete) Reset() {
	*x = SnapshotComplete{}
	mi := &file_v1_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotComplete) ProtoMessage() {}

func (x *SnapshotComplete) ProtoReflect() protoreflect.Message {
	mi := &file_v1_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotComplete.ProtoReflect.Descriptor instead.
func (*SnapshotComplete) Descriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotComplete) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

// Handshake identifies the serving peer region and advertised protocol version.
type Handshake struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// region is the serving peer region identity.
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// version is the serving peer version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// configuration is the serving peer configuration fingerprint.
	Configuration string `protobuf:"bytes,3,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_v1_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_v1_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{4}
}

func (x *Handshake) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Handshake) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Handshake) GetConfiguration() string {
	if x != nil {
		return x.Configuration
	}
	return ""
}

// SnapshotChunk carries a chunk of snapshot rows for one table.
type SnapshotChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// table is the replicated table name.
	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// rows contains the chunk rows in transfer order.
	Rows []*SnapshotRow `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	// last_chunk marks the final chunk for this snapshot stream.
	LastChunk bool `protobuf:"varint,3,opt,name=last_chunk,json=lastChunk,proto3" json:"last_chunk,omitempty"`
	// watermark is the sender-side catch-up boundary captured before snapshot streaming began.
	Watermark     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=watermark,proto3" json:"watermark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotChunk) Reset() {
	*x = SnapshotChunk{}
	mi := &file_v1_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunk) ProtoMessage() {}

func (x *SnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_v1_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunk.ProtoReflect.Descriptor instead.
func (*SnapshotChunk) Descriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{5}
}

func (x *SnapshotChunk) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SnapshotChunk) GetRows() []*SnapshotRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *SnapshotChunk) GetLastChunk() bool {
	if x != nil {
		return x.LastChunk
	}
	return false
}

func (x *SnapshotChunk) GetWatermark() *timestamppb.Timestamp {
	if x != nil {
		return x.Watermark
	}
	return nil
}

// SnapshotRow is one full row image within snapshot transfer.
type SnapshotRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// primary_key describes the row primary key in column order.
	PrimaryKey []*PrimaryKeyPart `protobuf:"bytes,1,rep,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	// payload is the encoded row payload.
	Fields map[string][]byte `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// metadata carries transit-only transformer state used during transport.
	// Entries under transit.* must be consumed before local persistence.
	Metadata      map[string][]byte `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRow) Reset() {
	*x = SnapshotRow{}
	mi := &file_v1_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRow) ProtoMessage() {}

func (x *SnapshotRow) ProtoReflect() protoreflect.Message {
	mi := &file_v1_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRow.ProtoReflect.Descriptor instead.
func (*SnapshotRow) Descriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotRow) GetPrimaryKey() []*PrimaryKeyPart {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

func (x *SnapshotRow) GetFields() map[string][]byte {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SnapshotRow) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// EventBatch is one ordered batch of incremental events for a table.
type EventBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sequence is the peer-local batch sequence for this table.
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// events contains the ordered incremental events in this batch.
	Events        []*Event `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_v1_replication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_v1_replication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{7}
}

func (x *EventBatch) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EventBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// TransactionBatch is one atomic CDC transaction delivered as a single batch.
// All events must be applied within a single database transaction on the receiver.
type TransactionBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sequence is the peer-local batch sequence shared across all tables.
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// tx_id is the source transaction identifier (LSN on PostgreSQL) used to
	// deduplicate redeliveries and correlate events to the originating transaction.
	TxId string `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// events contains the ordered incremental events in this batch.
	Events        []*Event `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionBatch) Reset() {
	*x = TransactionBatch{}
	mi := &file_v1_replication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionBatch) ProtoMessage() {}

func (x *TransactionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_v1_replication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionBatch.ProtoReflect.Descriptor instead.
func (*TransactionBatch) Descriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionBatch) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TransactionBatch) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TransactionBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// Event is one incremental row mutation.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_id is the stable event identifier used for acks and tracing.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// origin_region is the region that originally produced this event.
	OriginRegion string `protobuf:"bytes,2,opt,name=origin_region,json=originRegion,proto3" json:"origin_region,omitempty"`
	// table is the replicated table name.
	Table string `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	// primary_key describes the row primary key in column order.
	PrimaryKey []*PrimaryKeyPart `protobuf:"bytes,4,rep,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	// operation identifies whether the event is an upsert or delete.
	Operation Event_Operation `protobuf:"varint,5,opt,name=operation,proto3,enum=transmogr.peer.v1.Event_Operation" json:"operation,omitempty"`
	// payload is the encoded row payload for upserts.
	Fields map[string][]byte `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// metadata carries transit-only transformer state used during transport.
	// Entries under transit.* must be consumed before local persistence.
	Metadata map[string][]byte `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// version is the source ordering token.
	Version       int64 `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_v1_replication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_v1_replication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{9}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetOriginRegion() string {
	if x != nil {
		return x.OriginRegion
	}
	return ""
}

func (x *Event) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *Event) GetPrimaryKey() []*PrimaryKeyPart {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

func (x *Event) GetOperation() Event_Operation {
	if x != nil {
		return x.Operation
	}
	return Event_OPERATION_UNSPECIFIED
}

func (x *Event) GetFields() map[string][]byte {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Event) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Event) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// PrimaryKeyPart is one component of a possibly composite primary key.
type PrimaryKeyPart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// column is the source column name.
	Column string `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*PrimaryKeyPart_StringValue
	//	*PrimaryKeyPart_IntegerValue
	//	*PrimaryKeyPart_BooleanValue
	Value         isPrimaryKeyPart_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimaryKeyPart) Reset() {
	*x = PrimaryKeyPart{}
	mi := &file_v1_replication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimaryKeyPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimaryKeyPart) ProtoMessage() {}

func (x *PrimaryKeyPart) ProtoReflect() protoreflect.Message {
	mi := &file_v1_replication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimaryKeyPart.ProtoReflect.Descriptor instead.
func (*PrimaryKeyPart) Descriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{10}
}

func (x *PrimaryKeyPart) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *PrimaryKeyPart) GetValue() isPrimaryKeyPart_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PrimaryKeyPart) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*PrimaryKeyPart_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *PrimaryKeyPart) GetIntegerValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*PrimaryKeyPart_IntegerValue); ok {
			return x.IntegerValue
		}
	}
	return 0
}

func (x *PrimaryKeyPart) GetBooleanValue() bool {
	if x != nil {
		if x, ok := x.Value.(*PrimaryKeyPart_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return false
}

type isPrimaryKeyPart_Value interface {
	isPrimaryKeyPart_Value()
}

type PrimaryKeyPart_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type PrimaryKeyPart_IntegerValue struct {
	IntegerValue int64 `protobuf:"varint,3,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type PrimaryKeyPart_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,4,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

func (*PrimaryKeyPart_StringValue) isPrimaryKeyPart_Value() {}

func (*PrimaryKeyPart_IntegerValue) isPrimaryKeyPart_Value() {}

func (*PrimaryKeyPart_BooleanValue) isPrimaryKeyPart_Value() {}

// AckRequest confirms processing of all events up to the referenced last event id.
type AckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// region is the consuming peer region identity.
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// table is the replicated table name.
	Table string `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	// last_event_id is the last event id durably processed by the receiver.
	LastEventId   string `protobuf:"bytes,3,opt,name=last_event_id,json=lastEventId,proto3" json:"last_event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_v1_replication_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_replication_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{11}
}

func (x *AckRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AckRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *AckRequest) GetLastEventId() string {
	if x != nil {
		return x.LastEventId
	}
	return ""
}

// AckResponse confirms the acknowledgement was accepted.
type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_v1_replication_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_replication_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{12}
}

// Heartbeat is a keepalive and latency measurement message.
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sent_at is the sender timestamp for latency measurement.
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_v1_replication_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_v1_replication_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_v1_replication_proto_rawDescGZIP(), []int{13}
}

func (x *Heartbeat) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

var File_v1_replication_proto protoreflect.FileDescriptor

const file_v1_replication_proto_rawDesc = "" +
	"\n" +
	"\x14v1/replication.proto\x12\x11transmogr.peer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n" +
	"\x0eConsumeRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12$\n" +
	"\rconfiguration\x18\x03 \x01(\tR\rconfiguration\x12O\n" +
	"\x11snapshot_requests\x18\x04 \x03(\v2\".transmogr.peer.v1.SnapshotRequestR\x10snapshotRequests\"v\n" +
	"\x0fSnapshotRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12M\n" +
	"\x11after_primary_key\x18\x02 \x03(\v2!.transmogr.peer.v1.PrimaryKeyPartR\x0fafterPrimaryKey\"\xc9\x03\n" +
	"\x0fConsumeResponse\x12<\n" +
	"\thandshake\x18\x01 \x01(\v2\x1c.transmogr.peer.v1.HandshakeH\x00R\thandshake\x12I\n" +
	"\x0esnapshot_chunk\x18\x02 \x01(\v2 .transmogr.peer.v1.SnapshotChunkH\x00R\rsnapshotChunk\x12R\n" +
	"\x11snapshot_complete\x18\x06 \x01(\v2#.transmogr.peer.v1.SnapshotCompleteH\x00R\x10snapshotComplete\x12@\n" +
	"\vevent_batch\x18\x03 \x01(\v2\x1d.transmogr.peer.v1.EventBatchH\x00R\n" +
	"eventBatch\x12R\n" +
	"\x11transaction_batch\x18\x04 \x01(\v2#.transmogr.peer.v1.TransactionBatchH\x00R\x10transactionBatch\x12<\n" +
	"\theartbeat\x18\x05 \x01(\v2\x1c.transmogr.peer.v1.HeartbeatH\x00R\theartbeatB\x05\n" +
	"\x03msg\"(\n" +
	"\x10SnapshotComplete\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\"c\n" +
	"\tHandshake\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12$\n" +
	"\rconfiguration\x18\x03 \x01(\tR\rconfiguration\"\xb2\x01\n" +
	"\rSnapshotChunk\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x122\n" +
	"\x04rows\x18\x02 \x03(\v2\x1e.transmogr.peer.v1.SnapshotRowR\x04rows\x12\x1d\n" +
	"\n" +
	"last_chunk\x18\x03 \x01(\bR\tlastChunk\x128\n" +
	"\twatermark\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\twatermark\"\xd7\x02\n" +
	"\vSnapshotRow\x12B\n" +
	"\vprimary_key\x18\x01 \x03(\v2!.transmogr.peer.v1.PrimaryKeyPartR\n" +
	"primaryKey\x12B\n" +
	"\x06fields\x18\x02 \x03(\v2*.transmogr.peer.v1.SnapshotRow.FieldsEntryR\x06fields\x12H\n" +
	"\bmetadata\x18\x03 \x03(\v2,.transmogr.peer.v1.SnapshotRow.MetadataEntryR\bmetadata\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"Z\n" +
	"\n" +
	"EventBatch\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x120\n" +
	"\x06events\x18\x02 \x03(\v2\x18.transmogr.peer.v1.EventR\x06events\"u\n" +
	"\x10TransactionBatch\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x13\n" +
	"\x05tx_id\x18\x02 \x01(\tR\x04txId\x120\n" +
	"\x06events\x18\x03 \x03(\v2\x18.transmogr.peer.v1.EventR\x06events\"\xe1\x04\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12#\n" +
	"\rorigin_region\x18\x02 \x01(\tR\foriginRegion\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\x12B\n" +
	"\vprimary_key\x18\x04 \x03(\v2!.transmogr.peer.v1.PrimaryKeyPartR\n" +
	"primaryKey\x12@\n" +
	"\toperation\x18\x05 \x01(\x0e2\".transmogr.peer.v1.Event.OperationR\toperation\x12<\n" +
	"\x06fields\x18\x06 \x03(\v2$.transmogr.peer.v1.Event.FieldsEntryR\x06fields\x12B\n" +
	"\bmetadata\x18\a \x03(\v2&.transmogr.peer.v1.Event.MetadataEntryR\bmetadata\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversion\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"h\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OPERATION_INSERT\x10\x01\x12\x14\n" +
	"\x10OPERATION_UPDATE\x10\x02\x12\x14\n" +
	"\x10OPERATION_DELETE\x10\x03\"\xa4\x01\n" +
	"\x0ePrimaryKeyPart\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12%\n" +
	"\rinteger_value\x18\x03 \x01(\x03H\x00R\fintegerValue\x12%\n" +
	"\rboolean_value\x18\x04 \x01(\bH\x00R\fbooleanValueB\a\n" +
	"\x05value\"^\n" +
	"\n" +
	"AckRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\"\n" +
	"\rlast_event_id\x18\x03 \x01(\tR\vlastEventId\"\r\n" +
	"\vAckResponse\"@\n" +
	"\tHeartbeat\x123\n" +
	"\asent_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt2\xae\x01\n" +
	"\x12ReplicationService\x12R\n" +
	"\aConsume\x12!.transmogr.peer.v1.ConsumeRequest\x1a\".transmogr.peer.v1.ConsumeResponse0\x01\x12D\n" +
	"\x03Ack\x12\x1d.transmogr.peer.v1.AckRequest\x1a\x1e.transmogr.peer.v1.AckResponseB;Z9github.com/transmogr/transmogr/pkg/proto/transmogr/peerv1b\x06proto3"

var (
	file_v1_replication_proto_rawDescOnce sync.Once
	file_v1_replication_proto_rawDescData []byte
)

func file_v1_replication_proto_rawDescGZIP() []byte {
	file_v1_replication_proto_rawDescOnce.Do(func() {
		file_v1_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_replication_proto_rawDesc), len(file_v1_replication_proto_rawDesc)))
	})
	return file_v1_replication_proto_rawDescData
}

var file_v1_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_v1_replication_proto_goTypes = []any{
	(Event_Operation)(0),          // 0: transmogr.peer.v1.Event.Operation
	(*ConsumeRequest)(nil),        // 1: transmogr.peer.v1.ConsumeRequest
	(*SnapshotRequest)(nil),       // 2: transmogr.peer.v1.SnapshotRequest
	(*ConsumeResponse)(nil),       // 3: transmogr.peer.v1.ConsumeResponse
	(*SnapshotComplete)(nil),      // 4: transmogr.peer.v1.SnapshotComplete
	(*Handshake)(nil),             // 5: transmogr.peer.v1.Handshake
	(*SnapshotChunk)(nil),         // 6: transmogr.peer.v1.SnapshotChunk
	(*SnapshotRow)(nil),           // 7: transmogr.peer.v1.SnapshotRow
	(*EventBatch)(nil),            // 8: transmogr.peer.v1.EventBatch
	(*TransactionBatch)(nil),      // 9: transmogr.peer.v1.TransactionBatch
	(*Event)(nil),                 // 10: transmogr.peer.v1.Event
	(*PrimaryKeyPart)(nil),        // 11: transmogr.peer.v1.PrimaryKeyPart
	(*AckRequest)(nil),            // 12: transmogr.peer.v1.AckRequest
	(*AckResponse)(nil),           // 13: transmogr.peer.v1.AckResponse
	(*Heartbeat)(nil),             // 14: transmogr.peer.v1.Heartbeat
	nil,                           // 15: transmogr.peer.v1.SnapshotRow.FieldsEntry
	nil,                           // 16: transmogr.peer.v1.SnapshotRow.MetadataEntry
	nil,                           // 17: transmogr.peer.v1.Event.FieldsEntry
	nil,                           // 18: transmogr.peer.v1.Event.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_v1_replication_proto_depIdxs = []int32{
	2,  // 0: transmogr.peer.v1.ConsumeRequest.snapshot_requests:type_name -> transmogr.peer.v1.SnapshotRequest
	11, // 1: transmogr.peer.v1.SnapshotRequest.after_primary_key:type_name -> transmogr.peer.v1.PrimaryKeyPart
	5,  // 2: transmogr.peer.v1.ConsumeResponse.handshake:type_name -> transmogr.peer.v1.Handshake
	6,  // 3: transmogr.peer.v1.ConsumeResponse.snapshot_chunk:type_name -> transmogr.peer.v1.SnapshotChunk
	4,  // 4: transmogr.peer.v1.ConsumeResponse.snapshot_complete:type_name -> transmogr.peer.v1.SnapshotComplete
	8,  // 5: transmogr.peer.v1.ConsumeResponse.event_batch:type_name -> transmogr.peer.v1.EventBatch
	9,  // 6: transmogr.peer.v1.ConsumeResponse.transaction_batch:type_name -> transmogr.peer.v1.TransactionBatch
	14, // 7: transmogr.peer.v1.ConsumeResponse.heartbeat:type_name -> transmogr.peer.v1.Heartbeat
	7,  // 8: transmogr.peer.v1.SnapshotChunk.rows:type_name -> transmogr.peer.v1.SnapshotRow
	19, // 9: transmogr.peer.v1.SnapshotChunk.watermark:type_name -> google.protobuf.Timestamp
	11, // 10: transmogr.peer.v1.SnapshotRow.primary_key:type_name -> transmogr.peer.v1.PrimaryKeyPart
	15, // 11: transmogr.peer.v1.SnapshotRow.fields:type_name -> transmogr.peer.v1.SnapshotRow.FieldsEntry
	16, // 12: transmogr.peer.v1.SnapshotRow.metadata:type_name -> transmogr.peer.v1.SnapshotRow.MetadataEntry
	10, // 13: transmogr.peer.v1.EventBatch.events:type_name -> transmogr.peer.v1.Event
	10, // 14: transmogr.peer.v1.TransactionBatch.events:type_name -> transmogr.peer.v1.Event
	11, // 15: transmogr.peer.v1.Event.primary_key:type_name -> transmogr.peer.v1.PrimaryKeyPart
	0,  // 16: transmogr.peer.v1.Event.operation:type_name -> transmogr.peer.v1.Event.Operation
	17, // 17: transmogr.peer.v1.Event.fields:type_name -> transmogr.peer.v1.Event.FieldsEntry
	18, // 18: transmogr.peer.v1.Event.metadata:type_name -> transmogr.peer.v1.Event.MetadataEntry
	19, // 19: transmogr.peer.v1.Heartbeat.sent_at:type_name -> google.protobuf.Timestamp
	1,  // 20: transmogr.peer.v1.ReplicationService.Consume:input_type -> transmogr.peer.v1.ConsumeRequest
	12, // 21: transmogr.peer.v1.ReplicationService.Ack:input_type -> transmogr.peer.v1.AckRequest
	3,  // 22: transmogr.peer.v1.ReplicationService.Consume:output_type -> transmogr.peer.v1.ConsumeResponse
	13, // 23: transmogr.peer.v1.ReplicationService.Ack:output_type -> transmogr.peer.v1.AckResponse
	22, // [22:24] is the sub-list for method output_type
	20, // [20:22] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_v1_replication_proto_init() }
func file_v1_replication_proto_init() {
	if File_v1_replication_proto != nil {
		return
	}
	file_v1_replication_proto_msgTypes[2].OneofWrappers = []any{
		(*ConsumeResponse_Handshake)(nil),
		(*ConsumeResponse_SnapshotChunk)(nil),
		(*ConsumeResponse_SnapshotComplete)(nil),
		(*ConsumeResponse_EventBatch)(nil),
		(*ConsumeResponse_TransactionBatch)(nil),
		(*ConsumeResponse_Heartbeat)(nil),
	}
	file_v1_replication_proto_msgTypes[10].OneofWrappers = []any{
		(*PrimaryKeyPart_StringValue)(nil),
		(*PrimaryKeyPart_IntegerValue)(nil),
		(*PrimaryKeyPart_BooleanValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_replication_proto_rawDesc), len(file_v1_replication_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_replication_proto_goTypes,
		DependencyIndexes: file_v1_replication_proto_depIdxs,
		EnumInfos:         file_v1_replication_proto_enumTypes,
		MessageInfos:      file_v1_replication_proto_msgTypes,
	}.Build()
	File_v1_replication_proto = out.File
	file_v1_replication_proto_goTypes = nil
	file_v1_replication_proto_depIdxs = nil
}
